---
title: "Project 1"
author: "Brandon, Queena"
date: "September 15, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown 
## Objective 1: Display the ability to build regression models using the skills and discussions from Unit 1 and 2.   

```{r read and analyse the data}
library(ggplot2)

## Read in the CSV file
kc_data_df <- read.csv(file="C:/Users/chiawa/DS6372Project1_Group5/kc_house_data.csv", header=TRUE, sep=",")

## Remove all the NAs
kc_cleanData_df <-kc_data_df[rowSums(is.na(kc_data_df)) == 0,]
pairs (~price + bedrooms + bathrooms + sqft_lot + zipcode + view + floors + sqft_living, data = kc_cleanData_df)

## Try a log transformation with every relevant variable logged.
lprice <- log(kc_cleanData_df$price)
lbedrooms<-log(kc_cleanData_df$bedrooms)
lbathrooms<-log(kc_cleanData_df$bathrooms)
lsqft_lot<-log(kc_cleanData_df$sqft_lot)
lzipcode<-log(kc_cleanData_df$zipcode)
lview <- log(kc_cleanData_df$view)
lfloors<-log(kc_cleanData_df$floors)
lsqft_living<-log(kc_cleanData_df$sqft_living)

pairs (~lprice + lbedrooms + lbathrooms + lsqft_lot + lzipcode + lview + lfloors + lsqft_living, data = kc_cleanData_df)


## Try a sqrt transformation with every relevant variable logged.
sqrt_price <- sqrt(kc_cleanData_df$price)
sqrt_bedrooms<-sqrt(kc_cleanData_df$bedrooms)
sqrt_bathrooms<-sqrt(kc_cleanData_df$bathrooms)
sqrt_sqft_lot<-sqrt(kc_cleanData_df$sqft_lot)
sqrt_zipcode<-sqrt(kc_cleanData_df$zipcode)
sqrt_view <- sqrt(kc_cleanData_df$view)
sqrt_floors<-sqrt(kc_cleanData_df$floors)
sqrt_sqft_living<-sqrt(kc_cleanData_df$sqft_living)

pairs (~sqrt_price + sqrt_bedrooms + sqrt_bathrooms + sqrt_sqft_lot + sqrt_zipcode + sqrt_view + sqrt_floors + sqrt_sqft_living, data = kc_cleanData_df)

## Number of Bedroom vs Price
qplot(kc_cleanData_df$bedrooms, kc_cleanData_df$price,  data=kc_cleanData_df)
cor.test(kc_cleanData_df$bedrooms, kc_cleanData_df$price)

## Number of Bathrooms vs Price
qplot(kc_cleanData_df$bathrooms, kc_cleanData_df$price,data=kc_cleanData_df)
cor.test(kc_cleanData_df$bathrooms, kc_cleanData_df$price)

## sqft_lot of Bedroom vs Price
qplot(kc_cleanData_df$sqft_lot, kc_cleanData_df$price,  data=kc_cleanData_df)
cor.test(kc_cleanData_df$sqft_lot, kc_cleanData_df$price)

## zipcode vs price
qplot(kc_cleanData_df$zipcode,  kc_cleanData_df$price,   data=kc_cleanData_df)
cor.test(kc_cleanData_df$zipcode, kc_cleanData_df$price)

## view of Bedroom vs Price
qplot(kc_cleanData_df$view, kc_cleanData_df$price,  data=kc_cleanData_df)
cor.test(kc_cleanData_df$view, kc_cleanData_df$price)

## floors vs price
qplot(kc_cleanData_df$floors,  kc_cleanData_df$price,   data=kc_cleanData_df)
cor.test(kc_cleanData_df$floors, kc_cleanData_df$price)

## sqft_living vs Price
qplot(kc_cleanData_df$sqft_living, kc_cleanData_df$price,  data=kc_cleanData_df)
cor.test(kc_cleanData_df$sqft_living, kc_cleanData_df$price)

## sqft_living vs Price
qplot(kc_cleanData_df$yr_built, kc_cleanData_df$price,  data=kc_cleanData_df)
cor.test(kc_cleanData_df$yr_built, kc_cleanData_df$price)
```

```{r model 1 }
## model 1: using multi regression with two categorial variables (bathrooms number and sqft living)
model_1 <- lm(kc_cleanData_df$price ~ kc_cleanData_df$bathrooms + kc_cleanData_df$sqft_living , data = kc_cleanData_df)
summary(model_1)

#model_1_PI = predict(kc_cleanData_df.lm, interval="predict", newdata=kc_cleanData_df)
#model_1_PI

```
```{r model 1 residual analysis}
##plotting the model fit
par(mfrow=c(2,2))
plot(model_1 , which=c(1:3))

##Histogram with normal curve
##Store studentized residuals
model_1_studresbrain <- rstudent(model_1 )

##Histogram
hist(model_1_studresbrain, freq=FALSE, main="Distribution of Studentized Residuals(Model 1) ",
xlab="Studentized Residuals", ylab="Density", ylim=c(0,0.5))

##Create range of x-values for normal curve
xfit2 <- seq(min(model_1_studresbrain)-1, max(model_1_studresbrain)+1, length=40)

##Generate values from the normal distribution at the specified values
yfit2 <- (dnorm(xfit2))

##Add the normal curve
lines(xfit2, yfit2, ylim=c(0,0.5))

```
## model 2
```{r - use backward, forward, and stepwise to find the best model}
library(ggplot2)

## adjusted R^2 - higher is better
## MSPE (Mean Square Prediction Error) - lower is better as it measure the distance the prediction are from the acutual value


## model 2 with less varialbes
FitStart = lm(price ~ 1, data=kc_cleanData_df)

# Stepwise - Find the Model with lowest AIC
step(FitStart,direction="both", scope = formula(kc_cleanData_df))


#Step:  AIC=527906.5
#price ~ sqft_living + lat + view + grade + yr_built + waterfront + 
#    bedrooms + bathrooms + zipcode + long + condition + sqft_above + 
#    sqft_living15 + yr_renovated + sqft_lot15 + sqft_lot + floors

model_2 =lm(formula = price ~ sqft_living + lat + view + grade + yr_built + 
    waterfront + bedrooms + bathrooms + zipcode + long + condition + 
    sqft_above + sqft_living15 + yr_renovated + sqft_lot15 + 
    sqft_lot + floors, data = kc_cleanData_df)

```

## Object 2: Time Series

You can also embed plots, for example:

```{r correlation, echo=FALSE}
# compare models
#anova(model_1, model_2)
library(tseries)
library(forecast)
library(ggplot2)
library(dplyr)
library(ggmap)

kc_cleanData_df <-kc_data_df[rowSums(is.na(kc_data_df)) == 0,]
pairs (~price + bedrooms + bathrooms + sqft_lot + zipcode + view + floors + sqft_living, data = kc_cleanData_df)

# Drop Date From model
kc_cleanData_df <- kc_cleanData_df[,c(1,3:21)]
kc_cleanData_df

#Grab a smaller set of the data
kc_cleanData_df <- kc_cleanData_df[1:5000,]

attach(kc_cleanData_df)

glimpse(kc_cleanData_df)

summary(kc_cleanData_df)

pricesIn100k <- kc_cleanData_df$price /100000
hist(pricesIn100k,
     data=kc_cleanData_df,
     main = 'Price Distribution',
     xlab = 'Price in $100k',
     ylab = 'Frequency',
     col = 'red',
     bins =10
)

hist(kc_cleanData_df$bedrooms,
     main = 'Bedrooms Distribuion',
     xlab ='Number of Bedrroms',
     ylab = 'Frequency',
     col='blue'
     )
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
